//! Evaluates payloads generated by the server's buildSDKPayloadForConnection.
//! Regenerate with `node tests/scripts/generate_saved_group_payloads.cjs ../growthbook`.

use std::sync::Arc;
use std::time::Duration;

use growthbook_rust::cache::{FeatureCache, InMemoryCache};
use growthbook_rust::client::{GrowthBookClient, GrowthBookClientBuilder, GrowthBookClientTrait};
use growthbook_rust::dto::GrowthBookResponse;
use growthbook_rust::growthbook::GrowthBook;
use growthbook_rust::model_public::{FeatureResult, GrowthBookAttribute, SavedGroup};
use serde_json::{json, Value};
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

fn fixtures() -> Value {
    serde_json::from_str(include_str!("fixtures/saved_group_server_payloads.json")).expect("server-generated fixtures")
}

async fn serve(
    server: &MockServer,
    payload: &Value,
) {
    server.reset().await;
    Mock::given(method("GET"))
        .and(path("/api/features/server-payload-test"))
        .respond_with(ResponseTemplate::new(200).set_body_json(payload))
        .expect(1)
        .mount(server)
        .await;
}

fn builder(
    server: &MockServer,
    fixtures: &Value,
) -> GrowthBookClientBuilder {
    GrowthBookClientBuilder::new()
        .api_url(server.uri())
        .client_key("server-payload-test".to_owned())
        .auto_refresh(false)
        .ttl(Duration::ZERO)
        .decryption_key(fixtures["decryptionKey"].as_str().expect("test key").to_owned())
}

fn compare(
    client: &GrowthBookClient,
    fixtures: &Value,
    name: &str,
    mismatches: &mut Vec<String>,
) {
    compare_results(|key, attributes| client.feature_result(key, Some(attributes)), fixtures, name, mismatches);
}

fn compare_results(
    evaluate: impl Fn(&str, Vec<GrowthBookAttribute>) -> FeatureResult,
    fixtures: &Value,
    name: &str,
    mismatches: &mut Vec<String>,
) {
    for (index, evaluation) in fixtures["evaluations"].as_array().expect("evaluations").iter().enumerate() {
        let attributes = GrowthBookAttribute::from(evaluation["attributes"].clone()).expect("user attributes");
        for (key, expected) in evaluation["features"].as_object().expect("feature results") {
            let result = evaluate(key, attributes.clone());
            let experiment = result.experiment_result.map(|result| {
                json!({
                    "value": result.value,
                    "variationId": result.variation_id,
                    "inExperiment": result.in_experiment,
                    "hashUsed": result.hash_used,
                })
            });
            let actual = json!({
                "value": result.value, "on": result.on, "off": result.off,
                "source": result.source, "experimentResult": experiment,
            });
            if actual != *expected {
                mismatches.push(format!("{name}, user {index}, {key}: expected {expected}, got {actual}"));
            }
        }
    }
}

#[test]
fn server_payloads_evaluate_synchronously_without_a_runtime() {
    let fixtures = fixtures();
    let mut mismatches = Vec::new();
    for entry in fixtures["payloads"].as_array().expect("payloads") {
        if entry["name"].as_str().expect("format").ends_with("-encrypted") {
            continue;
        }
        let response: GrowthBookResponse = serde_json::from_value(entry["payload"].clone()).expect("response");
        let gb = GrowthBook {
            features: response.features.unwrap_or_default(),
            forced_variations: response.forced_variations,
            attributes: None,
            sticky_bucket_service: None,
            saved_groups: response
                .saved_groups
                .as_ref()
                .and_then(Value::as_object)
                .map(|groups| groups.iter().map(|(key, value)| (key.clone(), SavedGroup::from(value))).collect())
                .unwrap_or_default(),
        };
        compare_results(|key, attributes| gb.check(key, &Some(attributes)), &fixtures, entry["name"].as_str().unwrap(), &mut mismatches);
    }
    assert_parity(&mismatches);
}

#[test]
fn client_evaluates_after_setup_runtime_is_dropped() {
    let fixtures = fixtures();
    let runtime = tokio::runtime::Runtime::new().expect("runtime");
    let clients: Vec<_> = fixtures["payloads"]
        .as_array()
        .expect("payloads")
        .iter()
        .filter(|entry| !entry["name"].as_str().expect("format").ends_with("-encrypted"))
        .map(|entry| {
            let client = runtime
                .block_on(
                    GrowthBookClientBuilder::new()
                        .features_json(entry["payload"]["features"].clone())
                        .expect("features")
                        .saved_groups(entry["payload"]["savedGroups"].clone())
                        .build(),
                )
                .expect("client");
            (entry["name"].as_str().unwrap(), client)
        })
        .collect();
    drop(runtime);
    let mut mismatches = Vec::new();
    for (name, client) in clients {
        compare(&client, &fixtures, name, &mut mismatches);
    }
    assert_parity(&mismatches);
}

fn assert_parity(mismatches: &[String]) {
    assert!(
        mismatches.is_empty(),
        "{} mismatches:\n{}",
        mismatches.len(),
        mismatches.iter().take(20).cloned().collect::<Vec<_>>().join("\n")
    );
}

#[tokio::test]
async fn server_payloads_match_javascript_on_initial_load() {
    let fixtures = fixtures();
    let server = MockServer::start().await;
    let mut mismatches = Vec::new();
    for entry in fixtures["payloads"].as_array().expect("payloads") {
        serve(&server, &entry["payload"]).await;
        let client = builder(&server, &fixtures).build().await.expect("client loads server payload");
        compare(&client, &fixtures, entry["name"].as_str().expect("format"), &mut mismatches);
    }
    assert_parity(&mismatches);
}

#[tokio::test]
async fn server_payloads_match_javascript_when_refreshing_between_formats() {
    let fixtures = fixtures();
    let server = MockServer::start().await;
    let client = builder(&server, &fixtures).features_json(json!({})).expect("empty features").build().await.expect("client");
    let mut mismatches = Vec::new();
    for entry in fixtures["payloads"].as_array().expect("payloads") {
        serve(&server, &entry["payload"]).await;
        client.try_refresh().await.expect("refresh server payload");
        compare(&client, &fixtures, entry["name"].as_str().expect("format"), &mut mismatches);
    }
    assert_parity(&mismatches);
}

#[tokio::test]
async fn encrypted_server_payload_loads_from_cache() {
    let fixtures = fixtures();
    let server = MockServer::start().await;
    let cache = Arc::new(InMemoryCache::new(Duration::from_secs(60)));
    let payload = &fixtures["payloads"]
        .as_array()
        .expect("payloads")
        .iter()
        .find(|entry| entry["name"] == "referencesV2-encrypted")
        .expect("encrypted v2")["payload"];
    cache.set("features", serde_json::from_value(payload.clone()).expect("response")).await;
    let client = builder(&server, &fixtures).cache(cache).build().await.expect("cached encrypted response");
    let mut mismatches = Vec::new();
    compare(&client, &fixtures, "cached referencesV2-encrypted", &mut mismatches);
    assert_parity(&mismatches);
    assert!(server.received_requests().await.expect("requests").is_empty());
}

#[tokio::test]
async fn encrypted_payload_requires_the_correct_key() {
    let fixtures = fixtures();
    let server = MockServer::start().await;
    let payload = &fixtures["payloads"]
        .as_array()
        .expect("payloads")
        .iter()
        .find(|entry| entry["name"] == "referencesV2-encrypted")
        .expect("encrypted v2")["payload"];
    for key in [None, Some("ZmVkY2JhOTg3NjU0MzIxMA==")] {
        serve(&server, payload).await;
        let mut builder = GrowthBookClientBuilder::new().api_url(server.uri()).client_key("server-payload-test".to_owned());
        if let Some(key) = key {
            builder = builder.decryption_key(key.to_owned());
        }
        assert!(builder.build().await.is_err());
    }
}

#[tokio::test]
async fn invalid_encrypted_groups_preserve_features_and_do_not_enter_cache() {
    let fixtures = fixtures();
    let server = MockServer::start().await;
    let cache = Arc::new(InMemoryCache::new(Duration::from_secs(60)));
    let baseline = &fixtures["payloads"].as_array().expect("payloads").iter().find(|entry| entry["name"] == "referencesV2").expect("v2")["payload"];
    let client = builder(&server, &fixtures)
        .cache(cache.clone())
        .features_json(baseline["features"].clone())
        .expect("features")
        .saved_groups(baseline["savedGroups"].clone())
        .build()
        .await
        .expect("manual baseline");
    let mut invalid_groups = fixtures["invalidEncryptedSavedGroups"].as_array().expect("invalid encrypted fixtures").clone();
    invalid_groups.push(json!("invalid ciphertext"));
    for encrypted in invalid_groups {
        serve(&server, &json!({"features": {}, "encryptedSavedGroups": encrypted})).await;
        assert!(client.try_refresh().await.is_err());
        assert!(cache.get("features").await.is_none(), "invalid response must not poison cache");
        let mut mismatches = Vec::new();
        compare(&client, &fixtures, "state after rejected refresh", &mut mismatches);
        assert_parity(&mismatches);
    }
    serve(&server, baseline).await;
    client.try_refresh().await.expect("next valid response succeeds");
    assert!(cache.get("features").await.is_some());
}
